---
- name: Update packages on Debian-based systems
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
  when: ansible_facts['os_family'] == "Debian"

- name: Update packages on RedHat-based systems
  yum:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Update packages on Fedora-based systems
  dnf:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Fedora"

- name: Update packages on Arch-based systems
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Update packages on FreeBSD
  pkgng:
    state: latest
  when: ansible_facts['os_family'] == "FreeBSD"
