---
- name: Update packages on Debian-based systems
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages on Debian-based systems to their latest version
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.apt:
    name: "*"
    state: latest   # noqa: package-latest

- name: Update packages on RedHat-based-based systems
  when: ansible_facts['os_family'] == "RedHat"
  ansible.builtin.dnf:
    name: "*"
    state: latest   # noqa: package-latest
    update_cache: true

- name: Update packages on FreeBSD
  when: ansible_facts['os_family'] == "FreeBSD"
  community.general.pkgng:
    state: latest
