all:
  children:
    servers:
      hosts:  
        hyper-dave.prod.davidingwersen.com:
          ansible_host=192.168.1.253:
      vars:
        ansible_user: root
    
    hypervisors:
      hosts:
        esxi-dave.prod.davidingwersen.com: 
          ansible_host=192.168.1.254:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/ansible
    
    debian:
      hosts:
        tech-dns:
        TheDock: 
      vars:
        ansible_ssh_private_key_file: ~/.ssh/ansible
        ansible_user: david

    freebsd:
      hosts:
        pfsense: 
          ansible_host=192.168.1.1: 
          ansible_user=admin:
    
    switch:
      hosts:
        sw1.prod.davidingwersen.com: 
          ansible_host=192.168.1.3: 
          ansible_user=root: