---
plugin: community.general.proxmox
user: root@pam
url: "https://prox.prod.davidingwersen.com"
token_id: ansible
token_secret: "f5962cd1-73da-49e0-9a07-f868957f02f2"
want_facts: true
# qemu_extended_statuses: true

keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: tag_

groups:
  proxmox_use_agent: proxmox_agent == "1"
  proxmox_usable: (proxmox_status == "running") and ('linux' in (proxmox_tags|split(';'))) and (( proxmox_vmtype == "lxc" ) or ( proxmox_vmtype == "qemu" and proxmox_agent == "1" ))
#  webservers: "'web' in (proxmox_tags_parsed|list)"
#  mailservers: "'mail' in (proxmox_tags_parsed|list)"
#compose:
#  ansible_host: proxmox_net0["ip"].split('/')[0] if 'ip' in proxmox_net0 else proxmox_agent_interfaces[1]["ip-addresses"][0].split('/')[0]
  # ansible_port: 2222
#want_proxmox_nodes_ansible_host: true