---

- name: Install Docker on Debian-based systems
  become: true
  block:
    - name: Check if Docker is already installed
      ansible.builtin.shell: "docker --version"
      register: docker_installed
      failed_when: docker_installed.rc == 0
      changed_when: false
      ignore_errors: true

    - name: Abort if Docker is already installed
      ansible.builtin.fail:
        msg: "Docker is already installed on this host. Aborting to avoid disrupting running services."
      when: docker_installed.rc == 0

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name: "{{ docker_dependencies }}"
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure the /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: "{{ docker_repo_url }}/gpg"
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] {{ docker_repo_url }} {{ ansible_lsb.codename | lower }} stable"
        state: present

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        update_cache: true
        cache_valid_time: 3600
