- name: password change
  hosts: "debian"
  become: true
  vars_prompt:
  - name: new_password
    prompt: "Enter new password"
  tasks:
  - name: change user's password
    user:
      name: "david"
      update_password: always
      password: "{{ new_password|password_hash('sha512') }}"