- name: Set timezone and configure ntp
  hosts: "debian"
  become: true
  tasks:
  - name: Set timezone
    shell: timedatectl set-timezone America/New_York
  
  - name: Update repositories cache and install ntp package
    ansible.builtin.apt:
      name: ntp
      update_cache: yes
  
  - name: Stop service ntp, if running
    ansible.builtin.systemd:
      name: ntp
      state: stopped

  - name: Copy over ntp configuration
    template: src=../templates/ntp.conf dest=/etc/ntp.conf

  - name: Start service ntp on debian
    ansible.builtin.systemd:
      name: ntp
      state: started

  - name: Enable service ntp and ensure it is not masked
    ansible.builtin.systemd:
      name: ntp
      enabled: true
      masked: no