---
- name: Configure static DNS nameservers
  become: true
  block:
    - name: Remove resolvconf if present
      ansible.builtin.apt:
        name: resolvconf
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Check if resolv.conf is a symlink
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: resolv_conf_stat
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove the resolv.conf symlink if it exists
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
        force: true
      when:
        - ansible_facts['os_family'] == "Debian"
        - resolv_conf_stat.stat.islnk is defined and resolv_conf_stat.stat.islnk

    - name: Remove networkmanager if present
      ansible.builtin.apt:
        name: networkmanager
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove systemd-resolved if present
      ansible.builtin.apt:
        name: systemd-resolved
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Copy resolv.conf from the control node to the target host
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['os_family'] == "Debian"
      notify: restart networking
