---
- name: Configure static DNS nameservers
  become: true
  block:
    - name: Remove resolvconf if present
      apt:
        name: resolvconf
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove the resolv.conf symlink (if it exists)
      file:
        path: /etc/resolv.conf
        state: absent
        force: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove networkmanager if present
      apt:
        name: networkmanager
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove systemd-resolved if present
      apt:
        name: systemd-resolved
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Copy resolv.conf from the control node to the target host
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['os_family'] == "Debian"
      notify: restart networking