---
all:
  children:
    servers:
      hosts:
        hyper-dave.prod.davidingwersen.com:
          ansible_host: 192.168.1.253
      vars:
        ansible_user: root
    
    hypervisors:
      hosts:
        prox.prod.davidingwersen.com:
          ansible_host: 192.168.1.254
      vars:
        ansible_user: root

    debian:
      hosts:
        tech-dns.prod.davidingwersen.com:
          timezone: "America/New_York"
        thedock.prod.davidingwersen.com:
          timezone: "America/New_York"
        immich.prod.davidingwersen.com:
          timezone: "America/New_York"
        raspian.jp.davidingwersen.com:
          timezone: "Asia/Tokyo"

    freebsd:
      hosts:
        opnsense.prod.davidingwersen.com:
          ansible_host: 192.168.1.1
          ansible_user: root

    switch:
      hosts:
        sw1.prod.davidingwersen.com:
          ansible_host: 192.168.1.3
          ansible_user: root

    tailscale:
      hosts:
        tech-dns.prod.davidingwersen.com:
        thedock.prod.davidingwersen.com:
        immich.prod.davidingwersen.com:
        raspian.jp.davidingwersen.com: