---
all:
  children:
    servers:
      hosts:
        hyper-dave.prod.davidingwersen.com:
          ansible_host: 192.168.1.253
      vars:
        ansible_user: root
    
    hypervisors:
      hosts:
        prox.prod.davidingwersen.com:
          ansible_host: 192.168.1.254
      vars:
        ansible_user: root

    debian:
      hosts:
        tech-dns.prod.davidingwersen.com:
        thedock.prod.davidingwersen.com:
        immich.prod.davidingwersen.com:
        raspian.jp.davidingwersen.com:

    freebsd:
      hosts:
        opnsense.prod.davidingwersen.com:
          ansible_host: 192.168.1.1
          ansible_user: root

    switch:
      hosts:
        sw1.prod.davidingwersen.com:
          ansible_host: 192.168.1.3
          ansible_user: root

    tailscale:
      hosts:
        tech-dns.prod.davidingwersen.com:
        thedock.prod.davidingwersen.com:
        immich.prod.davidingwersen.com:
        raspian.jp.davidingwersen.com:

    prod_davidingwersen_com:
      hosts:
        tech-dns.prod.davidingwersen.com:
        thedock.prod.davidingwersen.com:
        immich.prod.davidingwersen.com:

    jp_davidingwersen_com:
      hosts:
        raspian.jp.davidingwersen.com: