---
all:
  children:
    servers:
      hosts:
        hyper-dave.prod.davidingwersen.com:
          ansible_host: 192.168.1.253
      vars:
        ansible_user: root
    
    hypervisors:
      hosts:
        prox.prod.davidingwersen.com:
          ansible_host: 192.168.1.254
      vars:
        ansible_user: root

    debian:
      hosts:
        tech-dns.prod.davidingwersen.com:
          ansible_host: 192.168.1.4
        tech-dns-bkup1.prod.davidingwersen.com:
          ansible_host: 192.168.1.5
        tech-dns-bkup2.prod.davidingwersen.com:
          ansible_host: 192.168.1.6
        debian-exit-node.prod.davidingwersen.com:
          ansible_host: 192.168.1.246
        stirling.prod.davidingwersen.com:
          ansible_host: 192.168.1.236
        paperless.prod.davidingwersen.com:
          ansible_host: 192.168.1.235
        apt-cacher.prod.davidingwersen.com:
          ansible_host: 192.168.1.234
        nginx.prod.davidingwersen.com:
          ansible_host: 192.168.1.7
        speed-test.prod.davidingwersen.com:
          ansible_host: 192.168.1.233
        thedock.prod.davidingwersen.com:
          ansible_host: 192.168.1.252
        immich.prod.davidingwersen.com:
          ansible_host: 192.168.1.248
        raspian.jp.davidingwersen.com:
          ansible_host: 192.168.0.251

    redhat:
      hosts:
        rhel.prod.davidingwersen.com:
          ansible_host: 192.168.1.210
        centos.prod.davidingwersen.com:
          ansible_host: 192.168.1.249

    freebsd:
      hosts:
        opnsense.prod.davidingwersen.com:
          ansible_host: 192.168.1.1
          ansible_user: root

    switch:
      hosts:
        sw1.prod.davidingwersen.com:
          ansible_host: 192.168.1.3
          ansible_user: root

    tailscale:
      hosts:
        tech-dns.prod.davidingwersen.com:
          ansible_host: 192.168.1.4
        thedock.prod.davidingwersen.com:
          ansible_host: 192.168.1.252
        immich.prod.davidingwersen.com:
          ansible_host: 192.168.1.248
        raspian.jp.davidingwersen.com:
          ansible_host: 192.168.0.251

    prod_davidingwersen_com:
      hosts:
        tech-dns.prod.davidingwersen.com:
          ansible_host: 192.168.1.4
        tech-dns-bkup1.prod.davidingwersen.com:
          ansible_host: 192.168.1.5
        tech-dns-bkup2.prod.davidingwersen.com:
          ansible_host: 192.168.1.6
        debian-exit-node.prod.davidingwersen.com:
          ansible_host: 192.168.1.246
        stirling.prod.davidingwersen.com:
          ansible_host: 192.168.1.236
        paperless.prod.davidingwersen.com:
          ansible_host: 192.168.1.235
        apt-cacher.prod.davidingwersen.com:
          ansible_host: 192.168.1.234
        nginx.prod.davidingwersen.com:
          ansible_host: 192.168.1.7
        speed-test.prod.davidingwersen.com:
          ansible_host: 192.168.1.233
        thedock.prod.davidingwersen.com:
          ansible_host: 192.168.1.252
        immich.prod.davidingwersen.com:
          ansible_host: 192.168.1.248
        rhel.prod.davidingwersen.com:
          ansible_host: 192.168.1.210
        centos.prod.davidingwersen.com:
          ansible_host: 192.168.1.249
          

    jp_davidingwersen_com:
      hosts:
        raspian.jp.davidingwersen.com:
          ansible_host: 192.168.0.251

    vms:
      hosts:
        thedock.prod.davidingwersen.com:
          ansible_host: 192.168.1.252
        immich.prod.davidingwersen.com:
          ansible_host: 192.168.1.248
        tech-dns.prod.davidingwersen.com:
          ansible_host: 192.168.1.4
        rhel.prod.davidingwersen.com:
          ansible_host: 192.168.1.210
        centos.prod.davidingwersen.com:
          ansible_host: 192.168.1.249
