---
- name: Check disk space
  hosts: "debian"

  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage

    - name: Print disk usage
      debug:
        msg: "The disk usage on {{ inventory_hostname }} is {{ disk_usage.stdout }}"