---
- name: Password Change
  hosts: "debian"
  become: true
  vars_prompt:
   - name: New Password
     prompt: "Enter new password"
  tasks:
   - name: Change User's Password
     user:
       name: "david"
       update_password: always
       password: "{{ new_password | password_hash('sha512') }}"
