---
- name: Ensure that ntp is installed, has the correct configuration file, and ntp is enabled.
  hosts: debian
  become: true
  tasks:
  - name: Set timezone to EST.
    shell: timedatectl set-timezone America/New_York
  
  - name: Update the local repository cache and install ntp package.
    ansible.builtin.apt:
      name: ntp
      update_cache: yes
  
  - name: Stop service ntp.
    ansible.builtin.systemd:
      name: ntp
      state: stopped

  - name: Copy over ntp configuration.
    template: src=../templates/ntp.conf dest=/etc/ntp.conf

  - name: Start service ntp.
    ansible.builtin.systemd:
      name: ntp
      state: started

  - name: Enable ntp service and ensure it is not masked.
    ansible.builtin.systemd:
      name: ntp
      enabled: true
      masked: no
